### ISSUE TITLE
luaview动画问题

### ISSUE THREAD

**Issue by aaaking** [alibaba/LuaViewSDK#11]
luaview设置Animation动画，如果先调用animation的方法start()之后，那么动画之后设置的callback属性无效，所以必须把方法start()放到callback之后执行。

**Comment by MonsterStorm** [comment]
这个我们下个版本讨论解决掉，至于是保留该方式还是引入新的特性，我们会在后续周知，请知悉。

**Comment by MonsterStorm** [comment]
问题已经解决
