### ISSUE TITLE
IOS最近都看没看到代码提交了，项目还打算维护吗？ 

### ISSUE THREAD

**Issue by freddiezhao** [alibaba/LuaViewSDK#12]
有计划是想更多的项目采用luaView的，但是使用过程中觉得引擎还有蛮多的地方不够完善，愿意做小白鼠，但是貌似没看到有新代码提交，心里觉得没底，如果不打算维护的话，让大家知悉啊，如果想继续推广，得建立个组织啥的，方便大家及时讨论

**Comment by dongxicheng** [comment]
1. LuaView开发节奏: 目前LuaViewSDK 按一个月一个版本的迭代方式前进;
2. 代码提交方式: 我们发布的代码都经过测试稳定后再统一提交到git上的
3. 非常欢迎使用LuaView我们内部已经线上使用超过半年了;
4. 暂定问题交流讨论组: https://gitter.im/alibaba/LuaViewSDK?utm_source=share-link&utm_medium=link&utm_campaign=share-link
