### ISSUE TITLE
lua for android

### ISSUE THREAD

**Issue by 908931448** [alibaba/LuaViewSDK#15]
按照文档说明 搭建了环境 跑起来是个空白页面 hello world没有打印出来

**Comment by MonsterStorm** [comment]
后台能看到关键字LuaView的相关日志么？

**Comment by Zhaoyy** [comment]
我也是遇到这个问题，请问新手入门里面的内容是否过时了

**Comment by Lamod** [comment]
在模拟器运行的时候，如果开启了debug但是没有打开debug桌面应用会阻塞luaview app执行

**Comment by Zhaoyy** [comment]
是的，我发现了。之前只是简单的通过注释来排查。
现在我发现了问题出在哪里了，在使用这个库的时候需要在下面的地方设置自己本地的ip地址。
修改类``com.taobao.luaview.debug.DebugConnection.java``
```java
public class DebugConnection extends Socket {

  private static final String EMULATOR_LOCALHOST = "your pc ip";
  private static final String GENYMOTION_LOCALHOST = "your pc ip";
```
如果你打开了调试器``LuaViewDebugger``那么这个时候就会弹出打印反馈信息的窗口，点击继续运行就ok了。

提个建议：这个地方对于新手可能不太友好，希望能够在新手教程里面能够说明白，这样也能避免其他网友的麻烦。

**Comment by Lamod** [comment]
这两个ip是给自带模拟器(EMULATOR_LOCALHOST)和genymotion模拟器(GENYMOTION_LOCALHOST)调试用的。  
创建LuaView实例的时候会根据LuaViewConfig.isOpenDebugger()来调用turnDebug，默认情况下在模拟器执行这个值才是true，也可以手动设为false。

**Comment by Zhaoyy** [comment]
@Lamod 我使用的是virtualbox安装的Android虚拟机，使用了桥接，所以可能这个ip就不合适。
刚刚使用as自带的模拟器发现，不需要修改，所以这里是我的问题。
谢谢，您的帮助解答：)
