### ISSUE TITLE
能不能给几个iOS和Android通用的列子

### ISSUE THREAD

**Issue by michaelxxw** [alibaba/LuaViewSDK#17]
如题，发觉两边的官方demo，写的都不一样，我在iOS上尝试写的一个demo，放到Android都不能正常显示，比如写了个tableview，设置的footer，直接跑到tableview的顶部去了，而在Android的RefreshTableView例子里，虽然然看到设置了header和footer，但显示不出来

**Comment by MonsterStorm** [comment]
你好，header和footer我们两边不打算支持，所以没做统一，后续这个功能会下掉。两边统一的demo我们正在整理放去，谢谢😃

**Comment by MonsterStorm** [comment]
最新文档，请参考: http://luaview.github.io
