### ISSUE TITLE
Image  网络图片  不显示网络图片

### ISSUE THREAD

**Issue by congni** [alibaba/LuaViewSDK#22]
同题
scrW, scrH = System.screenSize();
window.backgroundColor(0x777777,1);
local view = Image();
view.image("http://pic.sc.chinaz.com/files/pic/pic9/201508/apic14052.jpg");
view.backgroundColor(0xff0000,1);
w = scrW/3;
X0 = scrW/10;
Y0 = scrH/5;
view.frame(X0, Y0, w, w);

**Comment by Lamod** [comment]
iOS上吗? iOS 9之后默认只能使用https协议 [App Transport Security(ATS)](http://southpeak.github.io/blog/2015/09/14/app-transport-security-ats/)

**Comment by aoguo** [comment]
android image使用.image("https://..");不能显示图片

**Comment by MonsterStorm** [comment]
你好，使用的是demo工程么？如果是demo的话确认一下glide是否依赖成功，并且glide是否有报错信息？

**Comment by azxfire** [comment]
已经添加了允许http请求的key，但是图片还是不显示
