### ISSUE TITLE
luaView怎么做跳转传值？

### ISSUE THREAD

**Issue by jxtyq69** [alibaba/LuaViewSDK#23]
上传文件应该能实现吧。

跳转传值没有什么思路。我只会安卓，ios零基础，打算用这个开发公司产品，正在努力学lua、

**Comment by MonsterStorm** [comment]
你是说intent里面带参数么？目前luaview并没有强制跳转逻辑，你可以通过注入bridge来自定义页面跳转逻辑，可以自己定义想要处理的参数。bridge可以参考demo下的NUI_Bridge.lua
