### ISSUE TITLE
android Image 不显示网络图片

### ISSUE THREAD

**Issue by aoguo** [alibaba/LuaViewSDK#27]
android Image 不显示网络图片 使用http 和https都不行

**Comment by MonsterStorm** [comment]
请确认一下网络lib有下下来么？目前luaview使用的是谷歌官方图片库glide。如果使用的是demo工程的话会默认引用了，如果你是直接使用的sdk需要注入一个图片库，具体代码可以看看demo工程如何实现

**Comment by qujunnan2016** [comment]
如果你是直接使用的sdk需要注入一个图片库，具体代码可以看看demo工程如何实现.请问是什么图片库？SDWebImage吗？
