### ISSUE TITLE
error: package org.apache.http does not exist

### ISSUE THREAD

**Issue by zfbp** [alibaba/LuaViewSDK#29]
~~~
android{
    compileSdkVersion 23
    buildToolsVersion '23.0.1'
    useLibrary  'org.apache.http.legacy'
}
~~~

**Comment by 81813780** [comment]
> 编译完成后如果当前compileSdkVersion的版本是23（Adnroid 6.0）的情况会报错，因当前LuaViewSDK暂不支持6.0编译，需要将compileSdkVersion降一下，这里可以直接改两个module目录下的build.gradle文件。

建议你看下[新手文档](https://github.com/alibaba/LuaViewSDK/blob/master/Android/Documentation/%E6%96%B0%E6%89%8B%E5%85%A5%E9%97%A8-android/%E6%96%B0%E6%89%8B%E5%85%A5%E9%97%A8%20-%20android.md)

**Comment by zfbp** [comment]
新手文档我看过了，看到了不支持23。用22有其他错误。
谢谢！
