### ISSUE TITLE
关于作者对安卓部分何时开源的答复

### ISSUE THREAD

**Issue by freddiezhao** [alibaba/LuaViewSDK#3]
你好:
   很高兴你对我们的项目感兴趣,
   我们的LuaViewSDK Android, iOS版本都已经在线上运行,
   其中的LuaViewSDK Android版本也已经进入开源流程, 近期会放到github上. 
   欢迎到我们的wiki上问问题,我们后续会主要在wiki上进行沟通,这样可以帮助到有更多类似问题的同学.
   我们的wiki地址:
        https://github.com/alibaba/LuaViewSDK/wiki

谢谢你的来信.
祝好.
    ------------------------------------------------------------------
    主　题：luaViewSdk 学习请教

    你好，我是刚刚接触luaviewsdk的，觉得你们开源的这套引擎非常实用，对于luac的扩展已经可以看到有蛮多的demo了，luaj的扩展部分貌似还没有放出来，请问啥时间luaj这块能放出来扩展部分以及相关的demo来学习呢，我想把这套引擎使用到我们的项目里面去，盼回复，再次表示非常感谢！

**Comment by mazhao** [comment]
与问题#4重复，关闭。
