### ISSUE TITLE
作为类库项目，使用 GPL 协议是否不太合适？

### ISSUE THREAD

**Issue by drakeet** [alibaba/LuaViewSDK#31]
作为类库项目，GPL 开源协议规定使用者修改和新增代码都必须开源，并且新代码延续 GPL 协议，这样的话，只能用于开源项目了。

建议改成 LGPL(Library General Public License) 协议 或 Apache Licence 2.0，LGPL 协议和 GPL 的不同之处在于，对于库进行修改，需要遵循类似 GPL 的规定，而在非库项目中引用它，开发出来的新软件可以是私有的。

> “LGPL 是一个为主要为类库使用设计的开源协议，允许商业软件通过类库引用(link)方式使用 LGPL 类库而不需要开源商业软件的代码。这使得采用 LGPL 协议的开源代码可以被商业软件作为类库引用并发布和销售。”

**Comment by mazhao** [comment]
正在内部讨论，需要经过各种确认。稍安勿躁

**Comment by dongxicheng** [comment]
即将修改开源协议，内部正在审核中

**Comment by MonsterStorm** [comment]
协议已经修改为MIT，请放心使用，请知悉。
