### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by msy801006** [alibaba/LuaViewSDK#32]
Lua 脚本是源码打包进客户端的，对于root 或者 越狱的用户来说，就很容易获取到源码，不知道这方面问题该怎么处理？

**Comment by tangyiyang** [comment]
一般的思路是加密code，但是这个通常是防君子不防小人。因为可以hook require然后dump出require后的bytecode。

根本的解决方案还是只在 LuaView里做一些GUI的操作和非关键业务逻辑判断，重要的还是必须放在服务端。

2016-06-06 11:15 GMT+08:00 msy801006 <notifications@github.com>:

**Comment by msy801006** [comment]
@tangyiyang 感谢您的回答，LuaView仅做GUI的操作我也考虑过，可是luaView无法通过findViewById方法来获取到某个具体的控件，因此我只能把http request 放在 lua 脚本里，但这样就会将后端接口完全暴露出去了

**Comment by MonsterStorm** [comment]
@msy801006 可以通过bridge api的方式来操作native的view
