### ISSUE TITLE
System.screenSize 修改建议

### ISSUE THREAD

**Issue by msy801006** [alibaba/LuaViewSDK#33]
因为android有些设备会有虚拟功能键，而这部分高度将影响适配，脚本一致性，建议官方将这部分考虑进去。

如果我们自己修改，会牵涉到LuaView SDK 中 UDSystem.java 的调整，所以还是官方修改比较方便

**Comment by MonsterStorm** [comment]
好的，收到建议，预计最近版本修改掉（5.5.0）

谢谢反馈，：P
