### ISSUE TITLE
demo上面加载网络图片第一次不能显示，第二次进入才显示。我也存在这个问题。是为什么

### ISSUE THREAD

**Issue by qujunnan2016** [alibaba/LuaViewSDK#35]

**Comment by qujunnan2016** [comment]
急，在线等哦谢谢

**Comment by dongxicheng** [comment]
一下代码需要脚本运行前初始化，测试demo有错误：
    [LVButton setDefaultStyle:[JHSLVButton class]];
    [LVImage setDefaultStyle:[JHSLVImage class]];
    [LVCollectionView setDefaultStyle:[JHSLVCollectionView class]];
    [LVTableView setDefaultStyle:[JHSLVTableView class]];

**Comment by qujunnan2016** [comment]
ok，谢谢大神
