### ISSUE TITLE
请问有一套html转lua的工具吗

### ISSUE THREAD

**Issue by allentofight** [alibaba/LuaViewSDK#37]
用LuaView最常见的场景是配合运营配置的广告来实现动态更新

现在我有这么一个需求，我想设置一个网页工具，运营可以在上面自由拖拽UI，实现UI的自由搭配，完成后把网页上的UI布局自动转化为Lua脚本，请问你们有类似的工具吗

**Comment by MonsterStorm** [comment]
你好，暂时没有，你的功能可以通过预先写好几个模块lua代码，然后在网页端通过配置不同模块来实现。欢迎实现后贡献给开源组织。

谢谢反馈，：P
