### ISSUE TITLE
分享关于作者对安卓部分何时开源的答复

### ISSUE THREAD

**Issue by freddiezhao** [alibaba/LuaViewSDK#4]
你好:
   很高兴你对我们的项目感兴趣,
   我们的LuaViewSDK Android, iOS版本都已经在线上运行,
   其中的LuaViewSDK Android版本也已经进入开源流程, 近期会放到github上. 
   欢迎到我们的wiki上问问题,我们后续会主要在wiki上进行沟通,这样可以帮助到有更多类似问题的同学.
   我们的wiki地址:
        https://github.com/alibaba/LuaViewSDK/wiki

谢谢你的来信.
祝好.
    ------------------------------------------------------------------
    主　题：luaViewSdk 学习请教

    你好，我是刚刚接触luaviewsdk的，觉得你们开源的这套引擎非常实用，对于luac的扩展已经可以看到有蛮多的demo了，luaj的扩展部分貌似还没有放出来，请问啥时间luaj这块能放出来扩展部分以及相关的demo来学习呢，我想把这套引擎使用到我们的项目里面去，盼回复，再次表示非常感谢！

**Comment by mazhao** [comment]
Android 版本的 LuaViewSDK 现在正在内部 Review，会在3/15放出来，敬请期待。

**Comment by freddiezhao** [comment]
期待 。。。。

**Comment by BlankRain** [comment]
66666666666

**Comment by tommywu23** [comment]
@freddiezhao 老赵你可以把头像换下不？嘎嘎

**Comment by dongxicheng** [comment]
已经开源了
