### ISSUE TITLE
我要做个可以上下滚动的页面。上拉下拉刷新。 发现没有哪个ui容器合适的？

### ISSUE THREAD

**Issue by slxgsy** [alibaba/LuaViewSDK#40]
用RefreshTableView 的方法 不能设置每个cell的间隔miniSpacing，用RefreshCollectionView 又不能设置列表 顶部的内容。其他的ui容器也没看大合适的。怎么弄？有这样的demo吗？

**Comment by slxgsy** [comment]
问题解决了。不同的cell单独写模版

Cell = {
		Id = function ( section, row )
			if( row==1 ) then
				return "BannerLable";
			elseif( row==2 ) then
				return "NavigationLable";
			else
				return "ListLabel";
			end
		end,

**Comment by MonsterStorm** [comment]
上拉刷新可以考虑用一个cell来自动加载。
也可以扩展官方功能来实现。
