### ISSUE TITLE
attempt to index global 'viewController' (a nil value)

### ISSUE THREAD

**Issue by Inmay** [alibaba/LuaViewSDK#42]
找不到viewController,我该如何调用Controller的方法呢

**Comment by dongxicheng** [comment]
viewController是外部注册的一个native对象。取名iOS和安卓统一就可以，可以叫任意名字，没有注册就会找不到；
比如：
    // 注册 外部对象.
    self.lv[@"viewController"] = self;
lv是LView实例
@property(nonatomic, strong) LView *lv;

self.lv[@"任意名称"] = 任意实例;

**Comment by Inmay** [comment]
谢谢,setObject成功了
