### ISSUE TITLE
[LuaView][error]  IOS 教程demo报错

### ISSUE THREAD

**Issue by lvjj** [alibaba/LuaViewSDK#47]
按照文档上的流程走下来，运行报错

2016-07-29 15:43:16.699 HelloWordLuaViewSDK[4399:49718] [LuaView][error]   running chars == NULL, file: HelloWorld.lua

**Comment by dongxicheng** [comment]
[LuaView][error] running chars == NULL
表示找不到脚本

**Comment by dongxicheng** [comment]
[LuaView][error] running chars == NULL
表示找不到脚本

**Comment by lvjj** [comment]
刚读了下源码，发现在 _resourcePaths 的目录中没有找到lua文件

**Comment by lvjj** [comment]
另外，经调试发现
(lldb) po _resourcePaths
<__NSArrayM 0x7a94afa0>(
/Users/lvjj/Library/Developer/CoreSimulator/Devices/AB4FB20B-BBAF-4050-91FC-8275460F08A6/data/Containers/Data/Application/B211254B-9027-4641-AB2C-CD03861A065A/Library/Caches,
.
)

为何目录是在我电脑的路径

**Comment by lvjj** [comment]
`(lldb) po _scriptPaths
<__NSArrayM 0x7a94d730>(
.
)`
这是当前目录的意思？

**Comment by lvjj** [comment]
`(lldb) po _currentPath
/Users/lvjj/Library/Developer/CoreSimulator/Devices/AB4FB20B-BBAF-4050-91FC-8275460F08A6/data/Containers/Bundle/Application/33A5814F-B90B-4484-8837-8C217963CA18/HelloWordLuaViewSDK.app`

又是电脑路径？

**Comment by lvjj** [comment]
`lvjjdeMac:HelloWordLuaViewSDK.app lvjj$ pwd
/Users/lvjj/Library/Developer/CoreSimulator/Devices/AB4FB20B-BBAF-4050-91FC-8275460F08A6/data/Containers/Bundle/Application/33A5814F-B90B-4484-8837-8C217963CA18/HelloWordLuaViewSDK.app
lvjjdeMac:HelloWordLuaViewSDK.app lvjj$ ls
Base.lproj		HelloWorld.lua 		PkgInfo
Frameworks		Info.plist
HelloWordLuaViewSDK	MJRefresh.bundle
lvjjdeMac:HelloWordLuaViewSDK.app lvjj$ `

在电脑的目录发现这个文件

**Comment by lvjj** [comment]
`(lldb) po fullPath
/private/var/mobile/Containers/Bundle/Application/6DAAF49E-9D61-43C6-A45F-40475BF12EE1/HelloWordLuaViewSDK.app/./HelloWorld.lua

for (NSString *dir in _scriptPaths) {
        fullPath = [self absolutePath:[dir stringByAppendingPathComponent:name]];
        if ([_fileManager fileExistsAtPath:fullPath]) {
            return fullPath;
        }
    }`

发现问题，晕

**Comment by lvjj** [comment]
哈哈，以上找错记录都不算，原来是打错字了
HelloWord.lua  打成 HelloWorld.lua 
读了一遍源码，也不错了。。。。。

**Comment by lvjj** [comment]
最终发现
