### ISSUE TITLE
怎么用第三方组件，比如 luasql.sqlite3

### ISSUE THREAD

**Issue by lvjj** [alibaba/LuaViewSDK#48]
`ot found:
    no field package.preload['luasql.sqlite3']
    no file './luasql/sqlite3.so'
    no file '/usr/local/lib/lv/5.1/luasql/sqlite3.so'
    no file '/usr/local/lib/lv/5.1/loadall.so'
    no file './luasql.so'
    no file '/usr/local/lib/lv/5.1/luasql.so'
    no file '/usr/local/lib/lv/5.1/loadall.so'
`

**Comment by MonsterStorm** [comment]
你好，LuaView虚拟机暂时不是标准虚拟机。近期会切到标准虚拟机，后续直接引入第三方库使用。
