### ISSUE TITLE
Java 调用 Lua方法

### ISSUE THREAD

**Issue by DiaosiDev** [alibaba/LuaViewSDK#49]
java如何调用 lua方法  
UDView userData = mLuaView.getUserdata();
                if (userData != null) {
                    if (userData.getCallback() != null && userData.getCallback().istable()) {
                        LuaUtil.callFunction(LuaUtil.getFunction(userData.getCallback(), "testLua2Java"));
                    }
                }

function testLua2Java()
    print("testLua2Java")
end

不能调用   userData.getCallback()为空

还有可以问一下 如何在lua加载前传入数据 让lua在初始化的时候获取这些数据

**Comment by MonsterStorm** [comment]
1. 新版本LuaView可以使用LuaView.callLuaFunction(Object...params)或者LuaView.callWindowFunction(Object...params)来调用对应方法。
2. 换一个思路，可以考虑注册一个bridge，在lua运行的时候调用该bridge获取对应数据。

谢谢反馈，：P
