### ISSUE TITLE
luaViewSdk里面解析json有好的工具推荐一下吗

### ISSUE THREAD

**Issue by freddiezhao** [alibaba/LuaViewSDK#5]
如题，感谢

**Comment by freddiezhao** [comment]
lua解析json的工具类 有推荐的吗

**Comment by dongxicheng** [comment]
LuaViewSDK包含json解析API:
local str = "json格式的字符串"
local obj = Json.toTable(str);  --obj table

**Comment by shiguangkings** [comment]
cjson，毫无疑问

**Comment by hf19881120** [comment]
这个里面没cjson啊

**Comment by hf19881120** [comment]
感谢！ Json.toTable(str)这个可以用
但是官方的api里面没写啊

**Comment by shiguangkings** [comment]
@hf19881120 得自己集成

**Comment by shiguangkings** [comment]
@hf19881120  要是用lua自己的解析的速度比 cjson慢了十几几十倍
