### ISSUE TITLE
luaview内部大小计算问题

### ISSUE THREAD

**Issue by DiaosiDev** [alibaba/LuaViewSDK#50]
由于本人使用luaview控件只需要在部分位置进行展示  我在获取到luaview的真实大小后 在lua内获取真实大小在进行设置 不能够与真实大小相对应  而luaview直接用系统的尺寸进行设置 会导致部分view的位置不能掌控  在低分辨率尺寸下正好显示了  在高分辨率尺寸下 会导致底部大部分空白

**Comment by MonsterStorm** [comment]
你好，可以在创建LuaView的时候，指定LuaView的位置。
Android端通过设置Java端直接设置View的位置即可。
lua里也可以通过bridge，获取预定的位置进行定位。

另，LuaView使用的单位为dot（点）非px。请知悉。

谢谢反馈，：P
