### ISSUE TITLE
LuaViewSDK 为什么没有用OKHttp和fresco 

### ISSUE THREAD

**Issue by hechaohua** [alibaba/LuaViewSDK#51]
LuaViewSDK  为什么没有用OKHttp和fresco,如果要引入OKHttp和fresco是否需要改动源码？

**Comment by MonsterStorm** [comment]
你好，没有特殊原因，这一块开发者可以自由定制，图片库可以实现ImageProvider自行替换，请知悉。

谢谢反馈，：P
