### ISSUE TITLE
glide加载微信头像失败

### ISSUE THREAD

**Issue by letian003** [alibaba/LuaViewSDK#52]
一般的图片图都是.jpg, .png这种的
加载没问题，但是对于微信头象这种，  非这咱格式的， 显示不出来

**Comment by MonsterStorm** [comment]
1. 需要看一下Glide是否支持微信的头像格式
2. 考虑使用自己的图片库，扩展ImageProvider，具体使用参考http://luaview.github.io

谢谢反馈，：P
