### ISSUE TITLE
Luaview 锁屏之后闪屏情况

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/LuaViewSDK#53]
当手机锁屏之后重启，已下载好的图片，出现闪出背景色后又出现图片的情况

**Comment by MonsterStorm** [comment]
你好，LuaView 为了减少内存占用，在后台对图片做了内存清理，当View被 detach的时候会置空，如果想要禁用该功能，请修改BaseImageView， 去除releaseImage即可。

谢谢反馈，：P
