### ISSUE TITLE
AppStore  审核不通过

### ISSUE THREAD

**Issue by Hero2000** [alibaba/LuaViewSDK#55]
给公司的 app  加了 luaview 的模块   做好了  不过提交AppStore 审核不通过   官方有人知道怎么解决吗   已经先把这个 功能去掉了！！

From Apple
2. 5 PERFORMANCE: SOFTWARE REQUIREMENTS
Performance - 2.5.2

During review, your app downloaded Luascript code as part of the added LuaView SDK found in your app, which is no in compliance with the App Store Review Guidelines.

Next Steps

Please revise your app to remove this feature.

Resources

**Comment by sagiwei** [comment]
这就比较尴尬了啊

**Comment by Zhaoyy** [comment]
官方是如何解决的呢？

**Comment by ShixinPeng** [comment]
后续呢？在做技术调研，苹果应该是不会拒lua脚本，是针对这个SDk么

**Comment by Zhaoyy** [comment]
@ShixinPeng ios禁止的是通过这个sdk 下载lua脚本实现热更新。

**Comment by Hero2000** [comment]
不知道了！  我项目 就不准备用这个做热更新了   谁要是审核通过了  可以告诉一下

**Comment by tangyiyang** [comment]
根据从前做游戏时候的做法，在你提交审核的包里面，不要使用从Http加载的代码。

你可以后台做个开关，然后在通过审核后再转化成你需要的版本。

**Comment by tigerZhang86** [comment]
@Hero2000 你被拒的App，是在review时下载了Lua脚本才被发现的吗？
如果能保证在review期间不进行Lua脚本下载，等review审核通过后再后台开启是否可行？

**Comment by gubaojian** [comment]
LuaView SDK？ 连用的库名字都知道？

**Comment by MonsterStorm** [comment]
你好，建议对脚本代码进行加密处理。
