### ISSUE TITLE
vm好像有问题

### ISSUE THREAD

**Issue by jiasonwang** [alibaba/LuaViewSDK#57]
local a = "a";local b = "b"; if (a ~= nil) and (b ~= nil) then print("haha") end;
执行上面的代码，在命令行的lua下可以正常执行，但是在luaview里执行，却出现了错误：
test/testmy.lua org.luaj.vm2.LuaError: load test/testmy.lua: org.luaj.vm2.LuaError: test/testmy.lua:1: unexpected symbol 257 (ā)

**Comment by genehsun** [comment]
if (a ~= nil and b ~= nil) then    这样是可以的

**Comment by MonsterStorm** [comment]
LuaView目前使用的是非标准虚拟机。后续会切换到标准虚拟机，请知悉。

谢谢反馈，：P
