### ISSUE TITLE
这抄得有点太过了吧···连名字都不改啊····

### ISSUE THREAD

**Issue by zhaoyunman** [alibaba/LuaViewSDK#61]
![image](https://cloud.githubusercontent.com/assets/19965309/19373518/06a13232-91f7-11e6-89e3-b660672a47dc.png)

**Comment by DiaosiDev** [comment]
这是直接饮用的源码库...！！！

**Comment by tkggusraqk** [comment]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/view/ViewCompat$KitKatViewCompatImpl.class @DiaosiDev 这是什么错呀
，按着你们的教程搞的

**Comment by MonsterStorm** [comment]
@zhaoyunman 内部直接使用了facebook 的flex组件，可以让LuaView支持Flex布局。请知悉。

谢谢反馈，：P

**Comment by MonsterStorm** [comment]
@tkggusraqk 请确认一下Android环境正常，建议直接下载官方代码，然后使用AndroidStudio打开项目运行。另，确保gradle版本匹配。
