### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by tkggusraqk** [alibaba/LuaViewSDK#62]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/view/ViewCompat$KitKatViewCompatImpl.class

**Comment by MonsterStorm** [comment]
请确认一下Android运行环境正常。
谢谢反馈，：P
