### ISSUE TITLE
How to use VScrollView

### ISSUE THREAD

**Issue by bruceluliang** [alibaba/LuaViewSDK#65]
我使用VScrollView代码如下
scrollView = VScrollView();
scrollView.contentSize(w,h);
scrollView.xy(0,0);
scrollView.size(360,500);
scrollView.backgroundColor(MOCCASIN_COLOR);

view1 = View();
view1.frame(0,0,360,100);
--view1.flexCss("width: 300, height:100");
view1.backgroundColor(GREEN_COLOR);
scrollView.addView(view1);
但是界面没有任何反应，那么这个控件应该如何使用

**Comment by MonsterStorm** [comment]
你好，暂时没有VScrollView组件，只有HScrollView组件。如果要实现类似ScrollView效果的话，可以尝试使用CollectionView实现。
谢谢反馈，：P
