### ISSUE TITLE
timer在回调内部不执行

### ISSUE THREAD

**Issue by facetome** [alibaba/LuaViewSDK#66]
CurrentIndex = 0;
countTimer = Timer()
countTimer.callback(function()
    if (CurrentIndex < 3) then
        --本地图片直接加载,不会回调imageProvider
        lable.text(imageArray.get(CurrentIndex))
        imageView.image(imageArray.get(CurrentIndex),
            function()
            imageView.adjustSize()
            CurrentIndex = CurrentIndex + 1
        end)
    else
        CurrentIndex = CurrentIndex + 1
        bridge.finish(CurrentIndex)
--        无法关闭该定时器
        --countTimer.cancel()
    end
end)
countTimer.start(1, true)

**Comment by MonsterStorm** [comment]
图片回调已加，定时器会自动关闭，可以不用手工关闭。
谢谢反馈，：P
