### ISSUE TITLE
androidb版的网络请求会出现崩溃

### ISSUE THREAD

**Issue by star2heart** [alibaba/LuaViewSDK#67]
在CookieManager.java类的private static String getWebkitRequestCookies(String requestUrl)方法，网络请求时cookieManager.getCookie(requestUrl)会产生奔溃，处理的办法可以在此行前加上CookieSyncManager.createInstance(context).startSync();

**Comment by MonsterStorm** [comment]
已经同步，谢谢反馈。：P
