### ISSUE TITLE
请问动画 支持 旋转和移动同时进行吗？

### ISSUE THREAD

**Issue by Forceofwind** [alibaba/LuaViewSDK#68]
看了 支持 移动，旋转，缩放，但是支持同时进行吗？
还有好像没有 旋转的动画的例子，能增加下吗？

**Comment by MonsterStorm** [comment]
你好，支持。
有两种方式：
1. view.startAnimation(anim1, anim2)
2. 两个一起播
    Animation().alpha(1).with(view).start()
    Animation().translation(100, 100).with(view).start()
3. 旋转
    Animation().rotate(180).with(view).start()
