### ISSUE TITLE
LuaViewSDK 可以代替ios整个项目来实现吗

### ISSUE THREAD

**Issue by holyen** [alibaba/LuaViewSDK#9]
目前还有哪些不足和潜在的风险

**Comment by tommywu23** [comment]
貌似这个项目不热吖

**Comment by freddiezhao** [comment]
可以代替，我们公司就有部分项目是整个项目都采用luaViewSdk来开发的，不足就是文档不全，风险暂时还没发现

**Comment by lichunqiang** [comment]
文档不全，内部人是怎么使用的，看代码嘛？

**Comment by liuyin2004** [comment]
大家了解国内的deviceone产品吗？原理类似，但是已经支持lua和js，而且有快100个原生组件了，产品化已经很完善了。

**Comment by Zhaoyy** [comment]
@liuyin2004  开源吗？不开源也不是很敢用啊

**Comment by liuyin2004** [comment]
@Zhaoyy 开源了不少,最终会全部开源。可以参考github.com/do-android github.com/do-ios 。另外参考deviceone的主页吧

**Comment by slxgsy** [comment]
@freddiezhao 你们的项目上线了吗？整体性能如何呢？

**Comment by liuyin2004** [comment]
@slxgsy 你可以体验一下，性能很好，https://developer.deviceone.net/case 这里有一些客户开发的上线appstore的应用，你可以看看 慧影事件流 纳豆 。
示例代码可以参考： http://doc.deviceone.net/web/doc/code4do.htm

**Comment by wufeiafei** [comment]
怎样动态化下发lua文件，这一块文档好像也没写详细？
